#server {
#  listen 9145 default_server backlog=10240 reuseport;
#  server_name _;
#  charset utf-8;

#  access_log off;
#  error_log  logs/error.log;

#  include /etc/nginx/access.conf;

#  location = /metrics {
#    include /etc/nginx/access.conf;
#    access_log off;
#    content_by_lua_block {
#      metric_connections:set(ngx.var.connections_reading, {"reading"})
#      metric_connections:set(ngx.var.connections_waiting, {"waiting"})
#      metric_connections:set(ngx.var.connections_writing, {"writing"})
#      prometheus:collect()
#    }
#  }

#  location / {
#    return 200 "OK";
#  }
#}

server {
  listen 80 default_server backlog=10240 reuseport;
  #listen [::]:80 default_server backlog=10240 reuseport;
  #listen 443 ssl http2 default_server backlog=10240 reuseport;
  #listen [::]:443 ssl http2 default_server backlog=10240 reuseport

  server_name _;
  charset utf-8;

  access_log logs/access.log main;
  error_log  logs/error.log;

  #include /etc/nginx/ssl_base.conf;
  #include /etc/nginx/ssl_cert_default.conf;

  root  /etc/nginx/html;
  index index.html index.htm;

  #include /etc/nginx/error_page.conf;
  #include /etc/nginx/auth.conf;
  #include /etc/nginx/tools.conf;
  #include /etc/nginx/tips_test.conf;

  #modsecurity on;
  #modsecurity_rules '
  #  SecRuleEngine On
  #';
  #modsecurity_transaction_id "$req_id";
  #modsecurity_rules_file /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf;

  location = /favicon.ico { log_not_found off; access_log off; }
  location = /robots.txt { access_log off; return 200 "User-agent: *\nDisallow: /\n"; }

  location /healthz {
    access_log off;
    default_type text/plain;
    return 200 "";
  }

  #location /admin {
  #  #auth_request /auth;
  #  #error_page 401 =200 /login;
  #  proxy_pass http://192.168.100.100:8080;
  #  include /etc/nginx/proxy_params_ws;
  #}

  #location /error {
  #  log_not_found off;
  #  error_page 403 @error_page;
  #  return 403;
  #}

  location / {
    default_type text/plain;
    echo "OK";
  }
}
